version: '2'
services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    entrypoint: "mocha ./tests --recursive --reporter spec"
    volumes:
      - .:/src
    links:
        - db
  db:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - engine-mongo-data-test:/data/db:rw
volumes:
  engine-mongo-data-test: