version: '2'
services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/src
    links:
        - db
  db:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - engine-mongo-data-test:/data/db:rw
volumes:
  engine-mongo-data-test: